---

- name: include var inventory
  include_vars: "{{ inventory }}"

- name: check that download directory exist
  file:
    path: "{{ rec_download_directory }}"
    state: directory

- name: check that wav directory exist
  file:
    path: "{{ rec_wav_directory }}"
    state: directory

- name: check that json directory exist
  file:
    path: "{{ rec_json_directory }}"
    state: directory

- name: Template the python file for convert wav to json
  template:
    src: audiotofeatures.py.j2
    dest: "{{ root_dir }}/bin/audiotofeatures.py"
  
- include_tasks: ForEachBird.yml 
  with_items: 
        - "{{ birdRecList }}"
  loop_control:
    loop_var: bird
  


 



